change-details:
  coin-count: 100
  available-coins:
    - 0.01
    - 0.05
    - 0.10
    - 0.25
  allowedBills:
    - 1
    - 2
    - 5
    - 10
    - 20
    - 50
    - 100

logging.level:
  com.sample.billsexchange: DEBUG